# Generated by Django 5.2.7 on 2025-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=50)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
    ]
