# Generated by Django 5.2.7 on 2025-10-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
