# Generated by Django 5.2.7 on 2025-10-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
