# Generated by Django 5.2.7 on 2025-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='correo',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
