# Generated by Django 5.2.8 on 2025-11-06 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_creado_en_alter_student_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
